r=float(input("Nhap vao ban kinh cua duong tron:"))
s=float(3.14*r*r)
c=float(2*r*3.14)
print("Dien tich cua duong tron co ban kinh ",str(r)+"la =" ,round(s,2))
print("Chu vi cua duong tron co ban kinh ",str(r)+"la =",round(c,2))
